package dev.lizz.ytdl.core

import kotlin.jvm.JvmInline

/** Stable provider identifier used to route requests to a concrete site implementation. */
@JvmInline
public value class ProviderId(public val value: String) {
    override fun toString(): String = value

    public companion object {
        public val YOUTUBE: ProviderId = ProviderId("youtube")
    }
}

/** Options that control where the client writes the final audio file. */
public data class AudioDownloadOptions(
    val outputPath: String? = null,
)

/** Input for a single audio download request. */
public data class AudioDownloadRequest(
    val url: String,
    val provider: ProviderId? = null,
    val options: AudioDownloadOptions = AudioDownloadOptions(),
)

/** Input for transcript retrieval. */
public data class TranscriptRequest(
    val url: String,
    val provider: ProviderId? = null,
    val languageCode: String = "en",
    val includeTimecodes: Boolean = false,
)

/** Final result returned after a successful audio download. */
public data class AudioDownloadResult(
    val path: String,
    val fileName: String,
    val mimeType: String = "audio/mpeg",
    val metadata: MediaMetadata? = null,
    val provider: ProviderId,
)

/** High-level phases emitted while an audio download is running. */
public enum class MediaStage(public val label: String) {
    PrepareProvider("Prepare Provider"),
    ProbeMetadata("Probe Metadata"),
    DownloadAudio("Download Audio"),
    ConvertOutput("Convert Output"),
    Finalize("Finalize"),
}

/** Metadata resolved for the selected media item. */
public data class MediaMetadata(
    val title: String,
    val creator: String? = null,
    val durationSeconds: Int? = null,
    val durationText: String? = null,
    val sourceUrl: String,
    val availableAudioFormats: Int = 0,
    val bestAudioDescription: String? = null,
)

/** A single transcript cue with text and its original timing. */
public data class TranscriptCue(
    val startMs: Long,
    val endMs: Long,
    val text: String,
)

/** Structured transcript result for a single selected subtitle track. */
public data class TranscriptResult(
    val provider: ProviderId,
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val source: String,
    val cues: List<TranscriptCue>,
)

/** Transfer progress emitted during download and transcode work. */
public data class TransferSnapshot(
    val label: String = "Waiting to start",
    val progressPercent: Int? = null,
    val downloadedBytes: Long? = null,
    val totalBytes: Long? = null,
    val speedText: String? = null,
    val etaText: String? = null,
)

/** Stream of structured events produced while a download is running. */
public sealed interface MediaEvent {
    /** The provider entered a new high-level stage. */
    public data class StageChanged(val stage: MediaStage, val message: String) : MediaEvent

    /** Metadata was resolved before the media transfer started. */
    public data class MetadataResolved(val metadata: MediaMetadata) : MediaEvent

    /** A temporary working file path was created for the current transfer. */
    public data class WorkingFileResolved(val path: String) : MediaEvent

    /** The final output path was selected. */
    public data class OutputResolved(val path: String) : MediaEvent

    /** Download or transcode progress changed. */
    public data class ProgressChanged(val snapshot: TransferSnapshot) : MediaEvent

    /** Diagnostic output emitted by the provider. */
    public data class LogEmitted(val message: String) : MediaEvent

    /** The final output file is ready to use. */
    public data class Completed(val outputPath: String) : MediaEvent

    /** The operation failed with a terminal error. */
    public data class Failed(val message: String) : MediaEvent
}

/** Site-specific provider runtime used by the client registry. */
public interface MediaProvider {
    /** Stable provider identifier. */
    public val id: ProviderId

    /** Returns true when this provider can handle the supplied locator or URL. */
    public fun canHandle(locator: String): Boolean

    /** Downloads audio and emits progress updates. */
    public suspend fun downloadAudio(
        request: AudioDownloadRequest,
        emit: suspend (MediaEvent) -> Unit = {},
    ): AudioDownloadResult

    /** Returns transcript text when subtitles or captions are available. */
    public suspend fun getTranscript(request: TranscriptRequest): String?

    /** Returns structured transcript cues when subtitles or captions are available. */
    public suspend fun getTranscriptCues(request: TranscriptRequest): TranscriptResult?
}

/** Provider-aware public client API. */
public interface MediaClient {
    /** Downloads audio using the matching provider. */
    public suspend fun downloadAudio(
        request: AudioDownloadRequest,
        emit: suspend (MediaEvent) -> Unit = {},
    ): AudioDownloadResult

    /** Returns transcript text using the matching provider. */
    public suspend fun getTranscript(request: TranscriptRequest): String?

    /** Returns structured transcript cues using the matching provider. */
    public suspend fun getTranscriptCues(request: TranscriptRequest): TranscriptResult?
}

/** Default client implementation backed by an explicit provider registry. */
public class DefaultMediaClient(
    private val providers: List<MediaProvider>,
) : MediaClient {
    override suspend fun downloadAudio(
        request: AudioDownloadRequest,
        emit: suspend (MediaEvent) -> Unit,
    ): AudioDownloadResult {
        return resolveProvider(request.provider, request.url).downloadAudio(request, emit)
    }

    override suspend fun getTranscript(request: TranscriptRequest): String? {
        return resolveProvider(request.provider, request.url).getTranscript(request)
    }

    override suspend fun getTranscriptCues(request: TranscriptRequest): TranscriptResult? {
        return resolveProvider(request.provider, request.url).getTranscriptCues(request)
    }

    private fun resolveProvider(providerId: ProviderId?, url: String): MediaProvider {
        providerId?.let { requested ->
            return providers.firstOrNull { it.id == requested }
                ?: throw IllegalArgumentException("No provider registered for '${requested.value}'")
        }
        return providers.firstOrNull { it.canHandle(url) }
            ?: throw IllegalArgumentException("No registered provider can handle '$url'")
    }
}
