package dev.lizz.ytdl.providers.youtube

import dev.lizz.ytdl.core.ProviderId
import dev.lizz.ytdl.core.TranscriptCue
import dev.lizz.ytdl.core.TranscriptResult
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

internal data class TranscriptTrack(
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val source: String,
    val baseUrl: String,
)

internal object YoutubeTranscriptResolver {
    fun resolvePreferredTrack(
        initialPlayerResponse: JsonObject?,
        playerResponses: List<Pair<String, JsonObject>>,
        languageCode: String,
    ): TranscriptTrack? {
        val normalizedLanguage = languageCode.lowercase()
        return buildList {
            playerResponses.forEach { (source, player) -> addAll(extractTracks(player, source)) }
            addAll(extractTracks(initialPlayerResponse, "watch-page"))
        }
            .distinctBy { Triple(it.languageCode, it.isAutoGenerated, it.baseUrl) }
            .minByOrNull { trackPriority(it, normalizedLanguage) }
            ?.takeIf { trackPriority(it, normalizedLanguage) < Int.MAX_VALUE }
    }

    private fun trackPriority(track: TranscriptTrack, requestedLanguage: String): Int {
        val code = track.languageCode.lowercase()
        return when {
            !track.isAutoGenerated && code == requestedLanguage -> 0
            !track.isAutoGenerated && code.startsWith("$requestedLanguage-") -> 1
            track.isAutoGenerated && code == requestedLanguage -> 2
            track.isAutoGenerated && code.startsWith("$requestedLanguage-") -> 3
            else -> Int.MAX_VALUE
        }
    }

    private fun extractTracks(player: JsonObject?, source: String): List<TranscriptTrack> {
        val trackList = player?.objectAt("captions", "playerCaptionsTracklistRenderer") ?: return emptyList()
        return trackList.array("captionTracks").mapNotNull { trackElement ->
            val track = trackElement as? JsonObject ?: return@mapNotNull null
            val baseUrl = track.string("baseUrl") ?: return@mapNotNull null
            val rawLanguageCode = trackLanguageCode(track) ?: return@mapNotNull null
            val isAutoGenerated = track.string("kind") == "asr" || rawLanguageCode.startsWith("a-")
            val normalizedLanguageCode = rawLanguageCode.removePrefix("a-")
            TranscriptTrack(
                languageCode = normalizedLanguageCode,
                isAutoGenerated = isAutoGenerated,
                source = source,
                baseUrl = baseUrl,
            )
        }
    }

    private fun trackLanguageCode(track: JsonObject): String? {
        return track.string("vssId")
            ?.removePrefix(".")
            ?.replace('.', '-')
            ?.takeIf { it.isNotBlank() }
            ?: track.string("languageCode")
    }
}

internal object YoutubeWebVttParser {
    private val cueTiming = Regex(
        pattern = """^((?:\d+:)?\d{2}:\d{2}\.\d{3})\s+-->\s+((?:\d+:)?\d{2}:\d{2}\.\d{3})(?:\s+.*)?$"""
    )
    private val tagRegex = Regex("<[^>]+>")
    private val entityRegex = Regex("&#(x?[0-9A-Fa-f]+);")

    fun parse(vttText: String, languageCode: String, isAutoGenerated: Boolean, source: String): TranscriptResult {
        val normalized = vttText.replace("\r\n", "\n").replace('\r', '\n')
        val lines = normalized.lines()
        val cues = mutableListOf<TranscriptCue>()
        var index = 0

        while (index < lines.size) {
            val line = lines[index].trim()
            when {
                line.isBlank() || line == "WEBVTT" -> index++
                line.startsWith("NOTE") || line == "STYLE" || line == "REGION" -> {
                    index++
                    while (index < lines.size && lines[index].isNotBlank()) index++
                }
                cueTiming.matches(line) -> {
                    val match = cueTiming.matchEntire(line) ?: break
                    index++
                    val payloadLines = mutableListOf<String>()
                    while (index < lines.size && lines[index].isNotBlank()) {
                        payloadLines += lines[index]
                        index++
                    }
                    val text = cleanCueText(payloadLines.joinToString("\n"))
                    if (text.isNotBlank()) {
                        cues += TranscriptCue(
                            startMs = parseTimestampMs(match.groupValues[1]),
                            endMs = parseTimestampMs(match.groupValues[2]),
                            text = text,
                        )
                    }
                }
                else -> {
                    if (index + 1 < lines.size && cueTiming.matches(lines[index + 1].trim())) {
                        index++
                    } else {
                        index++
                    }
                }
            }
        }

        return TranscriptResult(
            provider = ProviderId.YOUTUBE,
            languageCode = languageCode,
            isAutoGenerated = isAutoGenerated,
            source = source,
            cues = normalizeCues(cues),
        )
    }

    private fun normalizeCues(cues: List<TranscriptCue>): List<TranscriptCue> {
        val out = mutableListOf<TranscriptCue>()
        for (cue in cues) {
            val previous = out.lastOrNull()
            if (previous == null) {
                out += cue
                continue
            }

            when {
                previous.text == cue.text -> {
                    out[out.lastIndex] = previous.copy(endMs = maxOf(previous.endMs, cue.endMs))
                }
                cue.text.startsWith(previous.text) -> {
                    val novel = trimLeadingContinuation(cue.text.removePrefix(previous.text))
                    if (novel.isBlank()) {
                        out[out.lastIndex] = previous.copy(endMs = maxOf(previous.endMs, cue.endMs))
                    } else {
                        out += cue.copy(text = novel)
                    }
                }
                previous.text.contains(cue.text) || previous.text.endsWith(cue.text) -> {
                    out[out.lastIndex] = previous.copy(endMs = maxOf(previous.endMs, cue.endMs))
                }
                else -> {
                    val overlap = longestSuffixPrefixOverlap(previous.text, cue.text)
                    if (overlap > 0) {
                        val novel = trimLeadingContinuation(cue.text.drop(overlap))
                        if (novel.isBlank()) {
                            out[out.lastIndex] = previous.copy(endMs = maxOf(previous.endMs, cue.endMs))
                        } else {
                            out += cue.copy(text = novel)
                        }
                    } else {
                        out += cue
                    }
                }
            }
        }
        return out
    }

    private fun trimLeadingContinuation(text: String): String {
        return text.trimStart().trimStart(',', '.', ';', ':', '!', '?', '-', ' ')
    }

    private fun longestSuffixPrefixOverlap(previous: String, current: String): Int {
        val maxLength = minOf(previous.length, current.length)
        for (length in maxLength downTo 1) {
            val suffixStart = previous.length - length
            val suffix = previous.substring(suffixStart)
            if (!current.startsWith(suffix)) continue
            if (!isBoundary(previous, suffixStart, previous.length)) continue
            if (!isBoundary(current, 0, length)) continue
            return length
        }
        return 0
    }

    private fun isBoundary(text: String, start: Int, end: Int): Boolean {
        val beforeOk = start == 0 || !text[start - 1].isLetterOrDigit()
        val afterOk = end >= text.length || !text[end].isLetterOrDigit()
        return beforeOk && afterOk
    }

    private fun parseTimestampMs(value: String): Long {
        val parts = value.split(':')
        val (hours, minutes, secondsPart) = when (parts.size) {
            2 -> Triple(0L, parts[0].toLong(), parts[1])
            3 -> Triple(parts[0].toLong(), parts[1].toLong(), parts[2])
            else -> error("Unsupported VTT timestamp: $value")
        }
        val secondParts = secondsPart.split('.')
        val seconds = secondParts[0].toLong()
        val millis = secondParts.getOrElse(1) { "0" }.padEnd(3, '0').take(3).toLong()
        return (((hours * 60 + minutes) * 60) + seconds) * 1000 + millis
    }

    private fun cleanCueText(raw: String): String {
        val withoutTags = tagRegex.replace(raw, "")
        val withoutEntities = decodeHtmlEntities(withoutTags)
        return withoutEntities
            .replace("\u00A0", " ")
            .lines()
            .map { it.trim() }
            .filter { it.isNotBlank() }
            .joinToString(" ")
            .replace(Regex("""\s+"""), " ")
            .trim()
    }

    private fun decodeHtmlEntities(value: String): String {
        val named = value
            .replace("&amp;", "&")
            .replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&quot;", "\"")
            .replace("&#39;", "'")
        return entityRegex.replace(named) { match ->
            val encoded = match.groupValues[1]
            val codePoint = if (encoded.startsWith("x", ignoreCase = true)) {
                encoded.drop(1).toIntOrNull(16)
            } else {
                encoded.toIntOrNull()
            }
            codePoint?.toChar()?.toString() ?: match.value
        }
    }
}

internal object YoutubeTranscriptFormatter {
    fun format(result: TranscriptResult, includeTimecodes: Boolean): String {
        val cues = result.cues
        return cues.joinToString("\n") { cue ->
            if (includeTimecodes) {
                "${formatTimestamp(cue.startMs)} --> ${formatTimestamp(cue.endMs)} ${cue.text}"
            } else {
                cue.text
            }
        }.trim()
    }

    private fun formatTimestamp(ms: Long): String {
        val totalSeconds = ms / 1000
        val millis = ms % 1000
        val seconds = totalSeconds % 60
        val minutes = (totalSeconds / 60) % 60
        val hours = totalSeconds / 3600
        return buildString {
            append(hours.toString().padStart(2, '0'))
            append(':')
            append(minutes.toString().padStart(2, '0'))
            append(':')
            append(seconds.toString().padStart(2, '0'))
            append('.')
            append(millis.toString().padStart(3, '0'))
        }
    }
}

internal fun buildTranscriptVttUrl(baseUrl: String): String {
    return if (Regex("""([?&])fmt=""").containsMatchIn(baseUrl)) baseUrl else {
        val separator = if ('?' in baseUrl) '&' else '?'
        "$baseUrl${separator}fmt=vtt"
    }
}

internal fun JsonObject.arrayObjects(key: String): List<JsonObject> = array(key).mapNotNull { it as? JsonObject }
internal fun JsonObject.textAt(vararg path: String): String? {
    val target = if (path.isEmpty()) this else objectAt(*path) ?: return null
    return target.string("simpleText") ?: target.arrayObjects("runs").joinToString("") { it.string("text").orEmpty() }.ifBlank { null }
}
