package dev.lizz.ytdl.providers.youtube.probe

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull

class YoutubeTranscriptPlannerTest {
    @Test
    fun `prefers manual exact language over auto and regional variants`() {
        val tracks = listOf(
            YoutubeTranscriptTrackCandidate(languageCode = "en", isAutoGenerated = true, source = "ios-player-api", baseUrl = "auto-en"),
            YoutubeTranscriptTrackCandidate(languageCode = "en-US", isAutoGenerated = false, source = "web-player-api", baseUrl = "manual-en-us"),
            YoutubeTranscriptTrackCandidate(languageCode = "en", isAutoGenerated = false, source = "watch-page", baseUrl = "manual-en"),
        )

        val selected = YoutubeTranscriptPlanner.selectTrack(tracks, "en")

        assertEquals("manual-en", selected?.baseUrl)
        assertFalse(selected?.isAutoGenerated ?: true)
    }

    @Test
    fun `returns null when requested language is missing`() {
        val tracks = listOf(
            YoutubeTranscriptTrackCandidate(languageCode = "en", isAutoGenerated = false, source = "watch-page", baseUrl = "manual-en"),
            YoutubeTranscriptTrackCandidate(languageCode = "es", isAutoGenerated = true, source = "ios-player-api", baseUrl = "auto-es"),
        )

        assertNull(YoutubeTranscriptPlanner.selectTrack(tracks, "fr"))
    }

    @Test
    fun `falls back from regional request to base manual language`() {
        val tracks = listOf(
            YoutubeTranscriptTrackCandidate(languageCode = "en", isAutoGenerated = false, source = "watch-page", baseUrl = "manual-en"),
            YoutubeTranscriptTrackCandidate(languageCode = "en", isAutoGenerated = true, source = "ios-player-api", baseUrl = "auto-en"),
        )

        assertEquals("manual-en", YoutubeTranscriptPlanner.selectTrack(tracks, "en-US")?.baseUrl)
    }
}
