package dev.lizz.ytdl.providers.youtube

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlinx.serialization.json.Json

class YoutubeTranscriptSupportTest {
    @Test
    fun `prefers manual english over auto english`() {
        val player = Json.parseToJsonElement(
            """
            {
              "captions": {
                "playerCaptionsTracklistRenderer": {
                  "captionTracks": [
                    {
                      "baseUrl": "https://example.com/auto-en",
                      "vssId": "a.en",
                      "languageCode": "en",
                      "kind": "asr"
                    },
                    {
                      "baseUrl": "https://example.com/manual-en",
                      "vssId": ".en",
                      "languageCode": "en"
                    }
                  ]
                }
              }
            }
            """.trimIndent()
        ).let { it as kotlinx.serialization.json.JsonObject }

        val track = YoutubeTranscriptResolver.resolvePreferredTrack(
            initialPlayerResponse = null,
            playerResponses = listOf("ios-player-api" to player),
            languageCode = "en",
        )

        assertNotNull(track)
        assertEquals("https://example.com/manual-en", track.baseUrl)
        assertEquals("en", track.languageCode)
        assertFalse(track.isAutoGenerated)
    }

    @Test
    fun `parses and cleans standalone webvtt transcript`() {
        val result = YoutubeWebVttParser.parse(
            vttText = """
                WEBVTT

                NOTE generated

                00:00:01.000 --> 00:00:03.000
                <c.colorE5E5E5>Hello &amp; welcome</c>

                00:00:03.000 --> 00:00:04.500
                <i>Hello &amp; welcome</i>

                cue-1
                00:00:05.000 --> 00:00:06.000 align:start
                Next line
                second row
            """.trimIndent(),
            languageCode = "en",
            isAutoGenerated = true,
            source = "ios-player-api",
        )

        assertEquals("en", result.languageCode)
        assertEquals(2, result.cues.size)
        assertEquals("Hello & welcome", result.cues[0].text)
        assertEquals(1_000L, result.cues[0].startMs)
        assertEquals(4_500L, result.cues[0].endMs)
        assertEquals("Next line second row", result.cues[1].text)
    }

    @Test
    fun `formats plain transcript without adjacent duplicates`() {
        val result = YoutubeWebVttParser.parse(
            vttText = """
                WEBVTT

                00:00:01.000 --> 00:00:02.000
                Same line

                00:00:02.000 --> 00:00:03.000
                Same line

                00:00:03.000 --> 00:00:04.000
                Different line
            """.trimIndent(),
            languageCode = "en",
            isAutoGenerated = true,
            source = "ios-player-api",
        )

        assertEquals(
            "Same line\nDifferent line",
            YoutubeTranscriptFormatter.format(result, includeTimecodes = false),
        )
        assertEquals(
            "00:00:01.000 --> 00:00:03.000 Same line\n00:00:03.000 --> 00:00:04.000 Different line",
            YoutubeTranscriptFormatter.format(result, includeTimecodes = true),
        )
    }

    @Test
    fun `collapses rolling auto caption overlap into novel cue text`() {
        val result = YoutubeWebVttParser.parse(
            vttText = """
                WEBVTT

                00:00:01.670 --> 00:00:01.680
                I have reached one year of unemployment

                00:00:01.680 --> 00:00:03.510
                I have reached one year of unemployment after graduation. It's genuinely rough,

                00:00:03.510 --> 00:00:03.520
                after graduation. It's genuinely rough,

                00:00:03.520 --> 00:00:05.030
                after graduation. It's genuinely rough, guys. There are days where I just want
            """.trimIndent(),
            languageCode = "en",
            isAutoGenerated = true,
            source = "ios-player-api",
        )

        assertEquals(
            listOf(
                "I have reached one year of unemployment",
                "after graduation. It's genuinely rough,",
                "guys. There are days where I just want",
            ),
            result.cues.map { it.text },
        )
        assertEquals(
            "I have reached one year of unemployment\nafter graduation. It's genuinely rough,\nguys. There are days where I just want",
            YoutubeTranscriptFormatter.format(result, includeTimecodes = false),
        )
    }
}
