package dev.lizz.ytdl.providers.youtube.probe

import dev.lizz.ytdl.core.MediaEvent
import dev.lizz.ytdl.core.MediaStage
import dev.lizz.ytdl.core.TranscriptRequest
import dev.lizz.ytdl.providers.youtube.PlayerJsDecipherer
import dev.lizz.ytdl.providers.youtube.ResolvedYoutubeMedia
import dev.lizz.ytdl.providers.youtube.YoutubeExtractorCommons
import dev.lizz.ytdl.providers.youtube.YoutubeWebVttParser
import dev.lizz.ytdl.providers.youtube.buildTranscriptVttUrl
import dev.lizz.ytdl.providers.youtube.errors.ProtectedFormatUnresolvedFailure
import dev.lizz.ytdl.providers.youtube.net.YoutubeResponseCache
import dev.lizz.ytdl.providers.youtube.net.YoutubeRetryPolicy

internal class YoutubeProbeService(
    private val commons: YoutubeExtractorCommons = YoutubeExtractorCommons(),
    private val cache: YoutubeResponseCache = YoutubeResponseCache(),
    private val clientRunner: YoutubePlayerClientRunner = YoutubePlayerClientRunner(commons, cache),
) {
    suspend fun probe(
        url: String,
        transport: YoutubeProbeTransport,
        context: YoutubeRequestContext = YoutubeRequestContext(),
        emit: suspend (MediaEvent) -> Unit = {},
    ): YoutubeProbeResult {
        emit(MediaEvent.StageChanged(MediaStage.PrepareProvider, "Resolving YouTube watch page in native Kotlin engine"))
        val watchPageHtml = cache.getOrLoad("watch:$url") {
            YoutubeRetryPolicy.run {
                transport.getText(url, defaultYoutubeTextHeaders(context))
            }
        }

        emit(MediaEvent.StageChanged(MediaStage.ProbeMetadata, "Parsing watch page and requesting Innertube player responses"))
        val watchData = commons.parseWatchData(url, watchPageHtml)
        return cache.getOrLoad("probe:${watchData.videoId}") {
            val apiPlayers = clientRunner.callPlayerApis(watchData.videoId, watchData.ytcfg, transport, emit)
            val initialResolved = commons.resolveMedia(url, watchData.initialPlayerResponse, apiPlayers)
            val resolvedMedia = attemptProtectedFormatResolution(initialResolved, watchData.playerUrl, transport, emit)
            YoutubeProbeResult(
                watchData = watchData,
                playerResponses = apiPlayers,
                resolvedMedia = resolvedMedia,
                transcriptTracks = YoutubeTranscriptPlanner.collectTracks(watchData.initialPlayerResponse, apiPlayers),
            )
        }
    }

    suspend fun getTranscriptCues(
        probe: YoutubeProbeResult,
        request: TranscriptRequest,
        transport: YoutubeProbeTransport,
        context: YoutubeRequestContext = YoutubeRequestContext(),
    ): dev.lizz.ytdl.core.TranscriptResult? {
        val track = YoutubeTranscriptPlanner.selectTrack(probe.transcriptTracks, request.languageCode) ?: return null
        val vttUrl = buildTranscriptVttUrl(track.baseUrl)
        val vttText = cache.getOrLoad("transcript:$vttUrl") {
            YoutubeRetryPolicy.run {
                transport.getText(
                    vttUrl,
                    buildMap {
                        put("User-Agent", userAgentForSource(track.source))
                        put("Accept-Language", context.acceptLanguage)
                        put("Accept-Encoding", "gzip, deflate")
                        put("Origin", "https://www.youtube.com")
                        put("Referer", probe.watchData.canonicalUrl)
                    },
                )
            }
        }
        return YoutubeWebVttParser.parse(vttText, track.languageCode, track.isAutoGenerated, track.source)
    }

    private suspend fun attemptProtectedFormatResolution(
        resolved: ResolvedYoutubeMedia,
        playerUrl: String?,
        transport: YoutubeProbeTransport,
        emit: suspend (MediaEvent) -> Unit,
    ): ResolvedYoutubeMedia {
        if (resolved.audioFormats.all { it.url != null } || playerUrl == null) return resolved

        emit(MediaEvent.LogEmitted("Protected audio formats detected; fetching player JS from $playerUrl"))
        val directBefore = resolved.audioFormats.count { it.url != null }
        val playerJs = cache.getOrLoad("playerjs:$playerUrl") {
            YoutubeRetryPolicy.run {
                transport.getText(
                    playerUrl,
                    mapOf(
                        "User-Agent" to YoutubeExtractorCommons.BROWSER_USER_AGENT,
                        "Accept-Encoding" to "gzip, deflate",
                    ),
                )
            }
        }
        val solvedFormats = PlayerJsDecipherer.resolveProtectedFormats(resolved.audioFormats, playerJs)
        val directAfter = solvedFormats.count { it.url != null }
        emit(MediaEvent.LogEmitted("Native signature solver resolved ${directAfter - directBefore} protected audio format(s)"))
        if (directBefore == 0 && directAfter == 0 && resolved.hlsManifestUrls.isEmpty() && resolved.dashManifestUrls.isEmpty()) {
            throw ProtectedFormatUnresolvedFailure()
        }
        return resolved.copy(audioFormats = solvedFormats)
    }
}
