package dev.lizz.ytdl.providers.youtube.probe

import dev.lizz.ytdl.providers.youtube.YoutubeTranscriptResolver

internal object YoutubeTranscriptPlanner {
    fun collectTracks(
        initialPlayerResponse: kotlinx.serialization.json.JsonObject?,
        playerResponses: List<Pair<String, kotlinx.serialization.json.JsonObject>>,
    ): List<YoutubeTranscriptTrackCandidate> {
        return YoutubeTranscriptResolver.collectTracks(initialPlayerResponse, playerResponses).map { track ->
            YoutubeTranscriptTrackCandidate(
                languageCode = track.languageCode,
                isAutoGenerated = track.isAutoGenerated,
                source = track.source,
                baseUrl = track.baseUrl,
            )
        }
    }

    fun selectTrack(
        tracks: List<YoutubeTranscriptTrackCandidate>,
        languageCode: String,
    ): YoutubeTranscriptTrackCandidate? {
        val normalizedLanguage = languageCode.lowercase()
        return tracks.minByOrNull { trackPriority(it, normalizedLanguage) }
            ?.takeIf { trackPriority(it, normalizedLanguage) < Int.MAX_VALUE }
    }

    private fun trackPriority(track: YoutubeTranscriptTrackCandidate, requestedLanguage: String): Int {
        val code = track.languageCode.lowercase()
        val requestedBase = requestedLanguage.substringBefore('-')
        val codeBase = code.substringBefore('-')
        return when {
            !track.isAutoGenerated && code == requestedLanguage -> 0
            !track.isAutoGenerated && code.startsWith("$requestedLanguage-") -> 1
            !track.isAutoGenerated && requestedLanguage.startsWith("$code-") -> 2
            !track.isAutoGenerated && codeBase == requestedBase -> 3
            track.isAutoGenerated && code == requestedLanguage -> 4
            track.isAutoGenerated && code.startsWith("$requestedLanguage-") -> 5
            track.isAutoGenerated && requestedLanguage.startsWith("$code-") -> 6
            track.isAutoGenerated && codeBase == requestedBase -> 7
            else -> Int.MAX_VALUE
        }
    }
}
