package dev.lizz.ytdl.providers.youtube.probe

import dev.lizz.ytdl.providers.youtube.ExtractedWatchData
import dev.lizz.ytdl.providers.youtube.NativeAudioFormat
import dev.lizz.ytdl.providers.youtube.NativeManifest
import dev.lizz.ytdl.providers.youtube.ResolvedYoutubeMedia
import kotlinx.serialization.json.JsonObject

internal data class YoutubeRequestContext(
    val acceptLanguage: String = "en-US,en;q=0.9",
)

internal data class YoutubeProbeResult(
    val watchData: ExtractedWatchData,
    val playerResponses: List<Pair<String, JsonObject>>,
    val resolvedMedia: ResolvedYoutubeMedia,
    val transcriptTracks: List<YoutubeTranscriptTrackCandidate>,
)

internal data class YoutubeAudioPlan(
    val preferredDirectFormat: NativeAudioFormat?,
    val directFormats: List<NativeAudioFormat>,
    val manifestFallbacks: List<NativeManifest>,
)

internal data class YoutubeTranscriptTrackCandidate(
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val source: String,
    val baseUrl: String,
)

internal interface YoutubeProbeTransport {
    suspend fun getText(url: String, headers: Map<String, String>): String

    suspend fun postJson(
        url: String,
        headers: Map<String, String>,
        body: JsonObject,
    ): JsonObject
}
